added 3 solutions to this answer
dimitryzub/stackoverflow-answers-archive pull request #7
Opened 2022-04-20 11:28 UTC by chukhraiartur

Dropped the code to check

2022-04-20 14:44 UTC, dimitryzub requested changes
@chukhraiartur Thanks for the new answer 👍🏻 Looks good. I've added minor suggestions. Thank you for adding an additional solution via Google API 🥇

Let's stick to our RP names as you did earlier: #5. 

So this `added 3 solutions to this answer` would become something like this: `[Stackoverflow] - scrape google organic results with user input`

___

The same goes for commits: `added 3 solutions to this answer` -> 3 separate commits:

```
git commit -m "add stackoverflow-webscraping-google-search-results-using-google-api-bs4.py"

git commit -m "add stackoverflow-webscraping-google-search-results-using-google-api-serpapi.py"

git commit -m "add stackoverflow-webscraping-google-search-results-using-google-api.py"
```
This way it would be much clearer to see what files you've added and easier to see commits history.  **This is a suggestion for the next PR, don't change in this one.**

___
Try to keep branch names as short as possible. 

Long names is not a big deal at all, just to make sure there's no unnecessary words like `returns-same-result-over-and-over-again`. So this branch could be something like this: `so-scrape-google-search-with-google-api-user-input`

2022-04-20 14:44 UTC, dimitryzub commented on answers/Artur/stackoverflow/google/python/stackoverflow-webscraping-google-search-results-using-google-api-bs4.py
> +}
```suggestion
# https://docs.python-requests.org/en/master/user/quickstart/#passing-parameters-in-urls
params = {
    "q": query,
    "hl": "en",  # language
    "gl": "us"   # country of the search, US -> USA
}
```


`hl` defines the language of the search and `gl` defines the country of the search. You can have a look at SerpApi's supported `hl` and `gl` parameters to have a better understanding:

 - `hl`: https://serpapi.com/google-languages
 - `gl`: https://serpapi.com/google-countries

2022-04-20 14:44 UTC, dimitryzub commented on answers/Artur/stackoverflow/google/python/stackoverflow-webscraping-google-search-results-using-google-api-bs4.py
> +    description = "Description == " + result.select_one(".VwiC3b").text
```suggestion
    title = f'Title: {result.select_one("h3").text}'
    link = f'Link: {result.select_one("a")["href"]}'
    description = f'Description: {result.select_one(".VwiC3b").text}'
```

[`f-string` is a pythonic way of concatenating string](https://stackoverflow.com/a/50474513/15164646) and looks cleaner. What do you think?

2022-04-20 14:44 UTC, dimitryzub commented on answers/Artur/stackoverflow/google/python/stackoverflow-webscraping-google-search-results-using-google-api-serpapi.py
> +}
```suggestion
params = {
  # https://docs.python.org/3/library/os.html#os.getenv
  "api_key": os.getenv("API_KEY"),  # your serpapi api key
  "engine": "google",               # search engine
  "q": query                        # search query
  # other parameters
}
```

Here you're describing what each parameter does and also mentioning that there are more available parameters `# other parameters`.

2022-04-20 14:44 UTC, dimitryzub commented on answers/Artur/stackoverflow/google/python/stackoverflow-webscraping-google-search-results-using-google-api-serpapi.py
> +results = search.get_dict()
```suggestion
search = GoogleSearch(params)  # where data extraction happens on the SerpApi backend
results = search.get_dict()    # JSON -> Python dict
```

2022-04-20 14:44 UTC, dimitryzub commented on answers/Artur/stackoverflow/google/python/stackoverflow-webscraping-google-search-results-using-google-api.py
> +for i in range(len(results)):
```suggestion
for i in results:
```
`len(range(<iterable>))` could be skipped in Python. `for results in results` is the same thing and as far as remember - faster💫

2022-04-20 14:44 UTC, dimitryzub commented on answers/Artur/stackoverflow/google/python/stackoverflow-webscraping-google-search-results-using-google-api.py
> +    print("Link == " + results['items'][i]['link'])
```suggestion
    print(f"Title == {results['items'][i]['title']}")
    print(f"Link == {results['items'][i]['link']}")
```
Same thing about `f-string` 👍🏻

2022-04-20 21:19 UTC, chukhraiartur commented
@dimitryzub I made your minor suggestions and added the .md file.

2022-04-21 07:39 UTC, dimitryzub reviewed
@chukhraiartur Awesome answer 💯 

Just a few text-related things to change.

2022-04-21 07:39 UTC, dimitryzub commented on answers/Artur/stackoverflow/google/python/stackoverflow-webscraping-google-search-results-using-google-api.md
> +Added [`f-string` is a pythonic way of concatenating strings](https://docs.python.org/3.6/reference/lexical_analysis.html#formatted-string-literals) that looks cleaner.
```suggestion

```

2022-04-21 07:39 UTC, dimitryzub commented on answers/Artur/stackoverflow/google/python/stackoverflow-webscraping-google-search-results-using-google-api.md
> +Below is a modified snippet of your code:
```suggestion
Below is a modified snippet of your code. I also added [`f-strings` which is a more pythonic way of concatenating strings](https://docs.python.org/3.6/reference/lexical_analysis.html#formatted-string-literals) that looks cleaner:
```

2022-04-21 07:39 UTC, dimitryzub commented on answers/Artur/stackoverflow/google/python/stackoverflow-webscraping-google-search-results-using-google-api.md
> +Variant that does the same but using only the [`Beautiful Soup`](https://beautiful-soup-4.readthedocs.io/en/latest/) library:
```suggestion
A solution that does the same but using only the [`Beautiful Soup`](https://beautiful-soup-4.readthedocs.io/en/latest/) library:
```

2022-04-21 07:39 UTC, dimitryzub commented on answers/Artur/stackoverflow/google/python/stackoverflow-webscraping-google-search-results-using-google-api.md
> +I decided to present an option using only the `Beautiful Soup` library, since your code uses a lot of libraries that you can do without. I also noticed that you manually remove the tags, although thi
```suggestion
I decided to present an option using only the `Beautiful Soup` library, since your code uses a lot of libraries that you can do without. I also noticed that you manually remove the tags, although this can be done more easily by selecting the text of the `.VwiC3b` selector. This will ignore the inner tags and take their contents.
```

What is `topmost` selector? Is it a mistake or done on purpose? I can't figure out what it is :) `.VwiC3b` is a selector from the screenshot you provided.

2022-04-21 12:04 UTC, chukhraiartur commented
@dimitryzub Thank you 😊
I made your changes, what do you say? 🤔

2022-04-21 12:41 UTC, dimitryzub approved these changes
@chukhraiartur Looks good to me 💯 

You can go ahead and merge this branch, publish an answer to StackOverflow and leave the link to your answer here as you did previously.

2022-04-21 12:45 UTC, merged

2022-04-21 12:46 UTC, chukhraiartur commented
https://stackoverflow.com/a/71954734/18597245