add google-ad-titles answer
dimitryzub/stackoverflow-answers-archive pull request #8
Opened 2022-05-09 17:34 UTC by Mykhailo-Zub

2022-05-10 13:35 UTC, dimitryzub requested changes
@Mykhailo-Zub, thank you for the answer💯 

I've added a few changes and a few things I want to point out. Tag me whenever changes will be applied.

I'll go ahead and mark it as a rejected answer.

2022-05-10 13:35 UTC, dimitryzub commented on answers/Mikhail/stackoverflow/google/google-search/google-ad/google-add-titles/answer.md
> +Check [my code in the online IDE][3].
```suggestion
```
Let's move it above, before the actual code.

2022-05-10 13:35 UTC, dimitryzub commented on answers/Mikhail/stackoverflow/google/google-search/google-ad/google-add-titles/answer.md
> +Check [my code in the online IDE][3].
```suggestion
```
Let's move it above, before the actual code.

2022-05-10 13:35 UTC, dimitryzub commented on answers/Mikhail/stackoverflow/google/google-search/google-ad/google-add-titles/answer.md
> +      .headers({ Accept: "application/json", "Content-Type": "application/json" })
```suggestion
      .headers({ "Accept": "application/json", "Content-Type": "application/json", "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36" })
```

2022-05-10 13:35 UTC, dimitryzub commented on answers/Mikhail/stackoverflow/google/google-search/google-ad/google-add-titles/answer.md
> +          titles[i] = $(el).find(".ZINbbc div.v5yQqb a.cz3goc div.CCgQ5 span").text();
```suggestion
          titles[i] = $(el).find(".v0nnCb span").text();
```

Changed to a shorter selector for Titles from Ad results.

2022-05-10 13:35 UTC, dimitryzub commented on answers/Mikhail/stackoverflow/google/google-search/google-ad/google-add-titles/answer.md
> +const search = new SerpApi.GoogleSearch("db088c5746dae73c45b3c1ce6cde6278af0e7aa38d2f0c0180db26174b5027dc");
```suggestion
const mySecret = process.env['API_KEY']
const search = new SerpApi.GoogleSearch(mySecret);
```
Is it your API key? If so, please, regenerate it and update on replit as well: https://serpapi.com/manage-api-key ✨

2022-05-10 13:35 UTC, dimitryzub commented on answers/Mikhail/stackoverflow/google/google-search/google-ad/google-add-titles/google-ad-titles-scrape-cheerio.js
> +      .headers({ Accept: "application/json", "Content-Type": "application/json" })
```suggestion
      .headers({ "Accept": "application/json", "Content-Type": "application/json", "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36" })
```

2022-05-10 13:35 UTC, dimitryzub commented on answers/Mikhail/stackoverflow/google/google-search/google-ad/google-add-titles/google-ad-titles-scrape-serpApi.js
> +const search = new SerpApi.GoogleSearch("db088c5746dae73c45b3c1ce6cde6278af0e7aa38d2f0c0180db26174b5027dc");
```suggestion
const mySecret = process.env['API_KEY']
const search = new SerpApi.GoogleSearch(mySecret);
```

2022-05-10 13:35 UTC, dimitryzub commented on answers/Mikhail/stackoverflow/google/google-search/google-ad/google-add-titles/google-ad-titles-scrape-serpApi.js
> +};
```suggestion
const params = {
  engine: "google",                         // search engine 
  q: "oxylabs",                             // search query
  location: "Austin, Texas, United States", // location parameter
  google_domain: "google.com",              // google domain of the search
  gl: "us",                                 // contry of the search
  hl: "en"                                  // language of the search  
};
```

2022-05-10 13:35 UTC, dimitryzub commented on answers/Mikhail/stackoverflow/google/google-search/google-ad/google-add-titles/google-ad-titles-scrape-serpApi.js
> +const SerpApi = require("google-search-results-nodejs");
```suggestion
// https://stackoverflow.com/questions/70853810/returned-null-response-from-unirest-block
// https://replit.com/@MikhailZub/Google-Ad-Results-with-NodeJS-SerpApi#index.js

const SerpApi = require("google-search-results-nodejs");
```

2022-05-10 13:35 UTC, dimitryzub commented on answers/Mikhail/stackoverflow/google/google-search/google-ad/google-add-titles/google-ad-titles-scrape-cheerio.js
> +const unirest = require("unirest");
```suggestion
// https://stackoverflow.com/questions/70853810/returned-null-response-from-unirest-block
// https://replit.com/@MikhailZub/Google-Ad-Results-with-NodeJS-SerpApi#index.js

const unirest = require("unirest");
```

Link to an answer and replit. This is helpful if you need to answer a similar question.

2022-05-10 13:35 UTC, dimitryzub commented on answers/Mikhail/stackoverflow/google/google-search/google-ad/google-add-titles/question.md
> +https://stackoverflow.com/questions/70853810/returned-null-response-from-unirest-block
Let's delete this file and add SO question to the [Cheerio](answers/Mikhail/stackoverflow/google/google-search/google-ad/google-add-titles/google-ad-titles-scrape-cheerio.js)/[SerpApi ](answers/Mikhail/stackoverflow/google/google-search/google-ad/google-add-titles/google-ad-titles-scrape-serpApi.js)solution answers. 

There's no need to create a separate file with a question.

2022-05-10 14:59 UTC, Mykhailo-Zub commented on answers/Mikhail/stackoverflow/google/google-search/google-ad/google-add-titles/answer.md
> +const search = new SerpApi.GoogleSearch("db088c5746dae73c45b3c1ce6cde6278af0e7aa38d2f0c0180db26174b5027dc");
Yes, it's my API key. Why i should regenerate it?

2022-05-11 04:56 UTC, dimitryzub commented on answers/Mikhail/stackoverflow/google/google-search/google-ad/google-add-titles/answer.md
> +Alternatively, you can use the [Google Ad Results API][1] from SerpApi. It solves captchas, rotates proxies, mimicking completely what a human will do. This guarantees that you get what users truly s
Makes sense 👍🏻 We need to change the wording in this part.

2022-05-11 05:02 UTC, dimitryzub commented on answers/Mikhail/stackoverflow/google/google-search/google-ad/google-add-titles/answer.md
> +const search = new SerpApi.GoogleSearch("db088c5746dae73c45b3c1ce6cde6278af0e7aa38d2f0c0180db26174b5027dc");
> Yes, it's my API key. Why I should regenerate it?

1. Users that don't have a SerpApi account can use your API directly without registering an account i.e not paying for it.
2. This is a potential vulnerability for hackers to access SerpApi. 

Please, regenerate it, and update the [replit repl](https://replit.com/@MikhailZub/Google-Ad-Results-with-NodeJS-SerpApi#index.js) as well.

2022-05-11 05:06 UTC, dimitryzub approved these changes
@Mykhailo-Zub That's great, thank you for the answer 🐳

You can go ahead and publish the answer to Stackoverflow. Once published, please, comment a link to your answer in this PR. [Here's an example from a different RP](https://github.com/dimitryzub/stackoverflow-answers-archive/pull/7#issuecomment-1105165128).

2022-05-11 10:18 UTC, merged

2022-05-11 10:19 UTC, Mykhailo-Zub commented
https://stackoverflow.com/questions/70853810/returned-null-response-from-unirest-block/72199294#72199294